source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'


#def Common
#
#  
#end


target 'StealthRocketVPN' do
  use_frameworks!
  
#  Common

  pod 'SnapKit'
  pod 'YYModel'
  pod 'AFNetworking'

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
